apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
data:
  configuration.yaml: |
    homeassistant:
      time_zone: "Europe/Berlin"
      unit_system: metric
    # add additional Home Assistant configuration here
  http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.12 # The IP address found in your error log
        - 127.0.0.1 # Always good practice for local loopback
        - ::1       # IPv6 loopback


